version: "2"
plugins:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - TODO
  rubocop:
    enabled: true
    # Locked channel/version to make sure it matches with version in the Gemfile. Update both when updating one.
    # Find available versions here: https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop
    channel: rubocop-1-23-0
  stylelint:
    enabled: true

exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"