AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 180
  Exclude:
    - 'spec/**/*'
    - 'Gemfile'

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 125
  CountAsOne:
    - heredoc

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'scripts/**/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: percent_r

Style/GuardClause:
  Enabled: false