version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

references:
  default_docker_ruby_executor: &default_docker_ruby_executor
    image: cimg/ruby:3.3.0
    environment:
      BUNDLE_PATH: vendor/bundle
      RAILS_ENV: test
      COVERAGE: true
      TZ: /usr/share/zoneinfo/America/Chicago
      CC_TEST_REPORTER_ID: f896cc968241a51947ba016bdc494b44e2a6e82a386fb73bf13e6436bc27a838

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: f896cc968241a51947ba016bdc494b44e2a6e82a386fb73bf13e6436bc27a838
    working_directory: ~/reporting_client/reporting_client_index
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - reporting_client-{{ checksum "reporting_client.gemspec" }}
            - reporting_client-
      - run:
          name: Bundle Install
          command: |
            gem install bundler -v 2.4.22
            bundle check || bundle install
      - save_cache:
          key: reporting_client-{{ checksum "reporting_client.gemspec" }}
          paths:
            - ~/reporting_client/reporting_client_index/vendor/bundle

  test:
    working_directory: ~/reporting_client/reporting_client_index
    parallelism: 1
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - reporting_client-{{ checksum "reporting_client.gemspec" }}
            - reporting_client-
      - run:
          name: Bundle Install
          command: |
            gem install bundler -v 2.4.22
            bundle check || bundle install
      - run:
          name: Run RSpec
          command: |
            mkdir /tmp/test-results
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      - codecov/upload
      - store_artifacts:
          path: coverage

  rubocop:
    working_directory: ~/reporting_client/reporting_client_index
    parallelism: 1
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - reporting_client-{{ checksum "reporting_client.gemspec" }}
            - reporting_client-
      - run:
          name: Bundle Install
          command: |
            gem install bundler -v 2.4.22
            bundle check || bundle install
      - run:
          name: rubocop
          command: |
            bundle exec rubocop

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build
