
version: 2

references:
  default_docker_ruby_executor: &default_docker_ruby_executor
    image: circleci/ruby:2.7.1-node-browsers
    environment:
      BUNDLE_PATH: vendor/bundle
      RAILS_ENV: test
      COVERAGE: true
      TZ: /usr/share/zoneinfo/America/Chicago
      CC_TEST_REPORTER_ID: f896cc968241a51947ba016bdc494b44e2a6e82a386fb73bf13e6436bc27a838

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: f896cc968241a51947ba016bdc494b44e2a6e82a386fb73bf13e6436bc27a838
    working_directory: ~/reporting_client/reporting_client_index
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - reporting_client-{{ checksum "reporting_client.gemspec" }}
            - reporting_client-
      - run:
          name: Bundle Install
          command: |
            gem install bundler
            bundle check || bundle install
      - save_cache:
          key: reporting_client-{{ checksum "reporting_client.gemspec" }}
          paths:
            - ~/reporting_client/reporting_client_index/vendor/bundle

  test:
    working_directory: ~/reporting_client/reporting_client_index
    parallelism: 1
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - reporting_client-{{ checksum "reporting_client.gemspec" }}
            - reporting_client-
      - run:
          name: Bundle Install
          command: |
            gem install bundler
            bundle check || bundle install
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run RSpec
          command: |
            mkdir /tmp/test-results
            ./cc-test-reporter before-build
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      - run:
          name: Code Climate Test Coverage
          command: |
            ./cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"
      - persist_to_workspace:
          root: coverage
          paths:
            - codeclimate.*.json
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: coverage

  rubocop:
    working_directory: ~/reporting_client/reporting_client_index
    parallelism: 1
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - reporting_client-{{ checksum "reporting_client.gemspec" }}
            - reporting_client-
      - run:
          name: Bundle Install
          command: |
            gem install bundler
            bundle check || bundle install
      - run:
          name: rubocop
          command: |
            bundle exec rubocop
  upload-coverage:
    working_directory: ~/reporting_client/reporting_client_index
    docker:
      - *default_docker_ruby_executor
    steps:
      - attach_workspace:
          at: ~/reporting_client/reporting_client_index
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Combine and Upload Coverage
          command: |
            ./cc-test-reporter sum-coverage --output - codeclimate.*.json | ./cc-test-reporter upload-coverage --debug --input -
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - upload-coverage:
          requires:
             - test